from __future__ import annotations

from datetime import datetime
from pathlib import Path

from agent.models import AssetIndex, AutomationAction, AutomationPlan, DeliveryPreparation, ProjectProfile


class AutomationPlanner:
    def build_plan(
        self,
        project_key: str,
        work_item_id: str,
        profile: ProjectProfile,
        asset_index: AssetIndex | None,
        delivery_package: DeliveryPreparation | None,
    ) -> AutomationPlan:
        source_psd = self._choose_source_psd(asset_index)
        stage_root = delivery_package.staged_root if delivery_package else None
        warnings: list[str] = []
        checks: list[str] = [
            "确认要打开的 PSD/PSB 是本次交付版本",
            "确认图层命名、按钮分层、导出尺寸和语言版本符合项目档案",
            "自动化只应在 staging 目录执行导出或复制动作，不直接覆盖正式文件",
        ]

        if not source_psd:
            warnings.append("未找到 PSD/PSB 源文件，Photoshop 自动化只能先输出检查清单")
        if not delivery_package:
            warnings.append("尚未生成交付 staging 包，导出动作建议先暂停")

        actions = [
            AutomationAction(
                step_id="A01",
                title="打开源文件",
                tool="photoshop",
                mode=profile.automation_preferences.get("photoshop_mode", "dry-run"),
                instruction=f"打开源文件：{source_psd or '待人工指定 PSD/PSB 路径'}",
                requires_confirmation=True,
            ),
            AutomationAction(
                step_id="A02",
                title="检查图层结构",
                tool="photoshop",
                mode="manual-checklist",
                instruction="确认 background / subject / copy / CTA / effects / exports 分组是否齐全。",
                depends_on=["A01"],
                requires_confirmation=True,
            ),
            AutomationAction(
                step_id="A03",
                title="检查项目强规则",
                tool="copilot",
                mode="audit",
                instruction=self._build_profile_rule_instruction(profile),
                depends_on=["A02"],
                requires_confirmation=True,
            ),
            AutomationAction(
                step_id="A04",
                title="导出到 staging",
                tool="photoshop",
                mode=profile.automation_preferences.get("export_mode", "staging-only"),
                instruction=(
                    f"按项目档案要求导出 {', '.join(profile.export_formats)} 到 staging 目录："
                    f"{stage_root or '待先运行 prepare-delivery-package'}"
                ),
                depends_on=["A03"],
                requires_confirmation=True,
            ),
            AutomationAction(
                step_id="A05",
                title="切图任务拆分",
                tool="copilot",
                mode="planning",
                instruction=self._build_slice_instruction(profile),
                depends_on=["A04"],
                requires_confirmation=True,
            ),
        ]

        return AutomationPlan(
            project_key=project_key,
            work_item_id=work_item_id,
            created_at=datetime.now().isoformat(timespec="seconds"),
            source_psd=source_psd,
            stage_root=stage_root,
            actions=actions,
            checks=checks,
            warnings=warnings,
        )

    @staticmethod
    def render_markdown(plan: AutomationPlan) -> str:
        lines = [
            f"# 自动化动作计划 - {plan.work_item_id}",
            "",
            f"- 项目：`{plan.project_key}`",
            f"- 创建时间：`{plan.created_at}`",
            f"- 源 PSD：`{plan.source_psd or '待指定'}`",
            f"- staging 目录：`{plan.stage_root or '待生成'}`",
            "",
            "## 动作列表",
        ]
        for action in plan.actions:
            lines.extend(
                [
                    f"### {action.step_id} {action.title}",
                    f"- 工具：`{action.tool}`",
                    f"- 模式：`{action.mode}`",
                    f"- 依赖：{', '.join(action.depends_on) if action.depends_on else '无'}",
                    f"- 需确认：{'是' if action.requires_confirmation else '否'}",
                    f"- 指令：{action.instruction}",
                    "",
                ]
            )
        lines.extend(["## 检查项", *(f"- {item}" for item in plan.checks)])
        lines.extend(["", "## 警告", *(f"- {item}" for item in plan.warnings or ["无"])])
        return "\n".join(lines)

    @staticmethod
    def render_powershell_stub(plan: AutomationPlan) -> str:
        lines = [
            "# Safe dry-run stub generated by design-copilot",
            f"# Project: {plan.project_key}",
            f"# Work Item: {plan.work_item_id}",
            "",
            "$ErrorActionPreference = 'Stop'",
            "$dryRun = $true",
            "",
        ]
        for action in plan.actions:
            lines.extend(
                [
                    f"Write-Host '[{action.step_id}] {action.title}'",
                    f"# Tool: {action.tool} | Mode: {action.mode}",
                    f"# Instruction: {action.instruction}",
                    "if (-not $dryRun) {",
                    "  # TODO: attach real Photoshop / GUI automation here",
                    "}",
                    "",
                ]
            )
        return "\n".join(lines)

    @classmethod
    def render_photoshop_jsx(cls, plan: AutomationPlan) -> str:
        source_psd = cls._jsx_string(plan.source_psd or "")
        stage_root = cls._jsx_string(plan.stage_root or "")
        checks = cls._jsx_array(plan.checks)
        warnings = cls._jsx_array(plan.warnings)
        project_key = cls._jsx_string(plan.project_key)
        work_item_id = cls._jsx_string(plan.work_item_id)
        created_at = cls._jsx_string(plan.created_at)
        return f"""// Generated by design-copilot.
// Safety contract:
// 1. Default mode is dry-run: it only opens/inspects the PSD and writes reports.
// 2. To export a flattened PNG preview, review the plan first and set allowExport to true.
// 3. The script writes only inside the selected staging folder and never overwrites the PSD.

#target photoshop

var CONFIG = {{
  projectKey: {project_key},
  workItemId: {work_item_id},
  createdAt: {created_at},
  sourcePsd: {source_psd},
  stageRoot: {stage_root},
  allowExport: false,
  checks: {checks},
  warnings: {warnings}
}};

function ensureFolder(folder) {{
  if (!folder.exists) {{
    folder.create();
  }}
  return folder;
}}

function writeTextFile(file, content) {{
  file.encoding = "UTF-8";
  file.open("w");
  file.write(content);
  file.close();
}}

function safeName(value) {{
  return String(value).replace(/[\\\\\\/:*?"<>|]+/g, "_").replace(/^\\s+|\\s+$/g, "") || "photoshop_export";
}}

function layerBounds(layer) {{
  try {{
    var b = layer.bounds;
    return [b[0].value, b[1].value, b[2].value, b[3].value].join(",");
  }} catch (e) {{
    return "unavailable";
  }}
}}

function collectLayers(container, depth, rows) {{
  for (var i = 0; i < container.layers.length; i += 1) {{
    var layer = container.layers[i];
    var indent = new Array(depth + 1).join("  ");
    var row = indent + "- " + layer.name + " | type=" + layer.typename + " | visible=" + layer.visible;
    if (layer.typename === "ArtLayer") {{
      row += " | opacity=" + layer.opacity + " | bounds=" + layerBounds(layer);
    }}
    rows.push(row);
    if (layer.typename === "LayerSet") {{
      collectLayers(layer, depth + 1, rows);
    }}
  }}
}}

function resolveSourceFile() {{
  if (CONFIG.sourcePsd) {{
    var configured = File(CONFIG.sourcePsd);
    if (configured.exists) {{
      return configured;
    }}
    alert("Configured PSD/PSB does not exist, please select it manually.\\n" + CONFIG.sourcePsd);
  }}
  return File.openDialog("Select the PSD/PSB for work item " + CONFIG.workItemId, "Photoshop:*.psd;*.psb");
}}

function resolveStageFolder() {{
  if (CONFIG.stageRoot) {{
    return ensureFolder(Folder(CONFIG.stageRoot));
  }}
  var selected = Folder.selectDialog("Select a staging folder for reports and optional exports");
  return selected ? ensureFolder(selected) : null;
}}

function main() {{
  app.bringToFront();
  var sourceFile = resolveSourceFile();
  if (!sourceFile) {{
    alert("No source PSD/PSB selected. Script stopped before making changes.");
    return;
  }}
  var stageFolder = resolveStageFolder();
  if (!stageFolder) {{
    alert("No staging folder selected. Script stopped before making changes.");
    return;
  }}

  var doc = app.open(sourceFile);
  var rows = [];
  collectLayers(doc, 0, rows);

  var report = [];
  report.push("# Photoshop Layer Report");
  report.push("");
  report.push("- Project: " + CONFIG.projectKey);
  report.push("- Work Item: " + CONFIG.workItemId);
  report.push("- Generated Plan: " + CONFIG.createdAt);
  report.push("- Source PSD: " + sourceFile.fsName);
  report.push("- Stage Folder: " + stageFolder.fsName);
  report.push("- Export Enabled: " + CONFIG.allowExport);
  report.push("");
  report.push("## Layers");
  report = report.concat(rows.length ? rows : ["- No layers found"]);
  report.push("");
  report.push("## Checks");
  for (var c = 0; c < CONFIG.checks.length; c += 1) {{
    report.push("- [ ] " + CONFIG.checks[c]);
  }}
  report.push("");
  report.push("## Warnings");
  if (CONFIG.warnings.length === 0) {{
    report.push("- None");
  }} else {{
    for (var w = 0; w < CONFIG.warnings.length; w += 1) {{
      report.push("- " + CONFIG.warnings[w]);
    }}
  }}

  writeTextFile(File(stageFolder.fsName + "/photoshop_layer_report.md"), report.join("\\n"));

  var checklist = [];
  checklist.push("# Slice Checklist");
  checklist.push("");
  checklist.push("- [ ] Confirm reusable groups: background / subject / copy / CTA / effects / exports");
  checklist.push("- [ ] Confirm button, title, icon, badge, logo, and language variants before slicing");
  checklist.push("- [ ] Confirm exported files use staging-only paths and final naming rules");
  checklist.push("- [ ] Designer approves before any formal handoff or overwrite");
  writeTextFile(File(stageFolder.fsName + "/photoshop_slice_checklist.md"), checklist.join("\\n"));

  if (!CONFIG.allowExport) {{
    alert("Dry-run complete. Reports written to staging.\\nNo image export was performed.\\nTo export a flattened PNG preview, review this script and set CONFIG.allowExport = true.");
    return;
  }}

  var duplicateName = safeName(CONFIG.projectKey + "_" + CONFIG.workItemId + "_flat_preview");
  var duplicate = doc.duplicate(duplicateName, true);
  var pngFile = File(stageFolder.fsName + "/" + duplicateName + ".png");
  var pngOptions = new PNGSaveOptions();
  duplicate.saveAs(pngFile, pngOptions, true, Extension.LOWERCASE);
  duplicate.close(SaveOptions.DONOTSAVECHANGES);
  alert("Export complete. Flattened PNG preview written to:\\n" + pngFile.fsName);
}}

main();
"""

    @staticmethod
    def render_photoshop_readme(plan: AutomationPlan) -> str:
        lines = [
            f"# Photoshop 脚本运行说明 - {plan.work_item_id}",
            "",
            "## 默认安全行为",
            "- `photoshop_export_dry_run.jsx` 默认只打开/检查 PSD，写出图层报告和切图清单。",
            "- 默认不会导出图片，不会保存 PSD，也不会覆盖正式文件。",
            "- 真正导出前，需要先人工审阅 `automation_plan.md` 与脚本内容。",
            "",
            "## 使用步骤",
            "1. 在 Photoshop 中打开 `File > Scripts > Browse...`。",
            "2. 选择 `photoshop_export_dry_run.jsx`。",
            "3. 按弹窗选择或确认 PSD/PSB 与 staging 目录。",
            "4. 先查看 staging 中生成的 `photoshop_layer_report.md` 和 `photoshop_slice_checklist.md`。",
            "5. 如果确认要导出预览图，再把 JSX 里的 `allowExport: false` 改为 `allowExport: true` 后重新运行。",
            "",
            "## 计划绑定",
            f"- 项目：`{plan.project_key}`",
            f"- 工作项：`{plan.work_item_id}`",
            f"- 源 PSD：`{plan.source_psd or '运行时手动选择'}`",
            f"- staging 目录：`{plan.stage_root or '运行时手动选择'}`",
            "",
            "## 警告",
        ]
        lines.extend(f"- {item}" for item in plan.warnings or ["无"])
        return "\n".join(lines)

    @staticmethod
    def _choose_source_psd(asset_index: AssetIndex | None) -> str | None:
        if not asset_index:
            return None
        preferred = [card for card in asset_index.asset_cards if card.extension in {".psd", ".psb"}]
        if not preferred:
            return None
        preferred.sort(key=lambda item: (item.role_guess != "source", item.role_guess != "key-visual", item.relative_path))
        return str(Path(asset_index.source_root) / preferred[0].relative_path)

    @staticmethod
    def _build_profile_rule_instruction(profile: ProjectProfile) -> str:
        if not profile.must_have_rules and not profile.forbidden_rules:
            return "项目档案暂无固定规则，请先补充后再做自动化执行。"
        parts: list[str] = []
        if profile.must_have_rules:
            parts.append("必须遵守：" + "；".join(profile.must_have_rules))
        if profile.forbidden_rules:
            parts.append("禁止出现：" + "；".join(profile.forbidden_rules))
        return " | ".join(parts)

    @staticmethod
    def _build_slice_instruction(profile: ProjectProfile) -> str:
        if not profile.slice_requirements:
            return "按按钮、底板、图标、角标等可复用元素拆分切图任务。"
        return "；".join(profile.slice_requirements)

    @staticmethod
    def _jsx_string(value: str) -> str:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'

    @classmethod
    def _jsx_array(cls, values: list[str]) -> str:
        return "[" + ", ".join(cls._jsx_string(value) for value in values) + "]"
